### ISSUE TITLE
Move to the attic?

### ISSUE THREAD

**Issue by jystewart** [alphagov/gds-warmup-controller#1]
Is anything using this any more? Seems like it's probably time to move it to the gds-attic organisation?

**Comment by alext** [comment]
I think we can, yes.  This only really makes sense when using Passenger, which we haven't been using since the days of the beta.

A [quick search](https://github.com/search?q=gds-warmup-controller+user%3Aalphagov&type=Code&utf8=%E2%9C%93) doesn't show anything that's using it.
